name: Experience Shiny
favicon: null
layout_spectrum: 0.027054250240325928
typography_spectrum: 0.4154415298253298
title: Experience Shiny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.26574715855531394
  lightness: 0.11204539309255779
  saturation: 0.47765218117274344
  rhythmicContrast: 0.05430553643964231
purpose: []
